version: "3.9"

services:
  startchat-controller:
    build:
      context: .
      dockerfile: Dockerfile
    image: startchat:latest
    ports:
      - "21001:21001"
    entrypoint: ["python3.9", "-m", "startchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  startchat-model-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    image: startchat:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ["python3.9", "-m", "startchat.serve.model_worker", "--model-names", "${STARTCHAT_WORKER_MODEL_NAMES:-vicuna-7b-v1.5}", "--model-path", "${STARTCHAT_WORKER_MODEL_PATH:-lmsys/vicuna-7b-v1.5}", "--worker-address", "http://startchat-model-worker:21002", "--controller-address", "http://startchat-controller:21001", "--host", "0.0.0.0", "--port", "21002"]
  startchat-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: startchat:latest
    ports:
      - "8000:8000"
    entrypoint: ["python3.9", "-m", "startchat.serve.openai_api_server", "--controller-address", "http://startchat-controller:21001", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  huggingface:
